import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/header';
const inter = Inter({ subsets: ['latin'] })

export default function Layout({children}: any){
    return(<>
            <Head>
                <title>Streaming Movies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link  rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css"/>
            </Head>
            <main>
                <Header></Header>
                <div className="p-6 mb-10">
                    {children}
                </div>
            </main>
        </>
    );
}

